# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/hellcat/plague/work-bench/CppPro/Pro/Netvideo

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/hellcat/plague/work-bench/CppPro/Pro/Netvideo

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/hellcat/plague/work-bench/CppPro/Pro/Netvideo/CMakeFiles /home/hellcat/plague/work-bench/CppPro/Pro/Netvideo/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/hellcat/plague/work-bench/CppPro/Pro/Netvideo/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named client_rtmp_admin

# Build rule for target.
client_rtmp_admin: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 client_rtmp_admin
.PHONY : client_rtmp_admin

# fast build rule for target.
client_rtmp_admin/fast:
	$(MAKE) -f CMakeFiles/client_rtmp_admin.dir/build.make CMakeFiles/client_rtmp_admin.dir/build
.PHONY : client_rtmp_admin/fast

#=============================================================================
# Target rules for targets named rtmp_cam_client

# Build rule for target.
rtmp_cam_client: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rtmp_cam_client
.PHONY : rtmp_cam_client

# fast build rule for target.
rtmp_cam_client/fast:
	$(MAKE) -f CMakeFiles/rtmp_cam_client.dir/build.make CMakeFiles/rtmp_cam_client.dir/build
.PHONY : rtmp_cam_client/fast

#=============================================================================
# Target rules for targets named ForSUNSEV_IoTtest2

# Build rule for target.
ForSUNSEV_IoTtest2: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ForSUNSEV_IoTtest2
.PHONY : ForSUNSEV_IoTtest2

# fast build rule for target.
ForSUNSEV_IoTtest2/fast:
	$(MAKE) -f CMakeFiles/ForSUNSEV_IoTtest2.dir/build.make CMakeFiles/ForSUNSEV_IoTtest2.dir/build
.PHONY : ForSUNSEV_IoTtest2/fast

#=============================================================================
# Target rules for targets named server

# Build rule for target.
server: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 server
.PHONY : server

# fast build rule for target.
server/fast:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/build
.PHONY : server/fast

#=============================================================================
# Target rules for targets named client-put

# Build rule for target.
client-put: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 client-put
.PHONY : client-put

# fast build rule for target.
client-put/fast:
	$(MAKE) -f CMakeFiles/client-put.dir/build.make CMakeFiles/client-put.dir/build
.PHONY : client-put/fast

#=============================================================================
# Target rules for targets named client-get

# Build rule for target.
client-get: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 client-get
.PHONY : client-get

# fast build rule for target.
client-get/fast:
	$(MAKE) -f CMakeFiles/client-get.dir/build.make CMakeFiles/client-get.dir/build
.PHONY : client-get/fast

#=============================================================================
# Target rules for targets named client-normal

# Build rule for target.
client-normal: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 client-normal
.PHONY : client-normal

# fast build rule for target.
client-normal/fast:
	$(MAKE) -f CMakeFiles/client-normal.dir/build.make CMakeFiles/client-normal.dir/build
.PHONY : client-normal/fast

client-get.o: client-get.cpp.o

.PHONY : client-get.o

# target to build an object file
client-get.cpp.o:
	$(MAKE) -f CMakeFiles/client-get.dir/build.make CMakeFiles/client-get.dir/client-get.cpp.o
.PHONY : client-get.cpp.o

client-get.i: client-get.cpp.i

.PHONY : client-get.i

# target to preprocess a source file
client-get.cpp.i:
	$(MAKE) -f CMakeFiles/client-get.dir/build.make CMakeFiles/client-get.dir/client-get.cpp.i
.PHONY : client-get.cpp.i

client-get.s: client-get.cpp.s

.PHONY : client-get.s

# target to generate assembly for a file
client-get.cpp.s:
	$(MAKE) -f CMakeFiles/client-get.dir/build.make CMakeFiles/client-get.dir/client-get.cpp.s
.PHONY : client-get.cpp.s

client-normal.o: client-normal.cpp.o

.PHONY : client-normal.o

# target to build an object file
client-normal.cpp.o:
	$(MAKE) -f CMakeFiles/client-normal.dir/build.make CMakeFiles/client-normal.dir/client-normal.cpp.o
.PHONY : client-normal.cpp.o

client-normal.i: client-normal.cpp.i

.PHONY : client-normal.i

# target to preprocess a source file
client-normal.cpp.i:
	$(MAKE) -f CMakeFiles/client-normal.dir/build.make CMakeFiles/client-normal.dir/client-normal.cpp.i
.PHONY : client-normal.cpp.i

client-normal.s: client-normal.cpp.s

.PHONY : client-normal.s

# target to generate assembly for a file
client-normal.cpp.s:
	$(MAKE) -f CMakeFiles/client-normal.dir/build.make CMakeFiles/client-normal.dir/client-normal.cpp.s
.PHONY : client-normal.cpp.s

client_rtmp_admin.o: client_rtmp_admin.cpp.o

.PHONY : client_rtmp_admin.o

# target to build an object file
client_rtmp_admin.cpp.o:
	$(MAKE) -f CMakeFiles/client_rtmp_admin.dir/build.make CMakeFiles/client_rtmp_admin.dir/client_rtmp_admin.cpp.o
.PHONY : client_rtmp_admin.cpp.o

client_rtmp_admin.i: client_rtmp_admin.cpp.i

.PHONY : client_rtmp_admin.i

# target to preprocess a source file
client_rtmp_admin.cpp.i:
	$(MAKE) -f CMakeFiles/client_rtmp_admin.dir/build.make CMakeFiles/client_rtmp_admin.dir/client_rtmp_admin.cpp.i
.PHONY : client_rtmp_admin.cpp.i

client_rtmp_admin.s: client_rtmp_admin.cpp.s

.PHONY : client_rtmp_admin.s

# target to generate assembly for a file
client_rtmp_admin.cpp.s:
	$(MAKE) -f CMakeFiles/client_rtmp_admin.dir/build.make CMakeFiles/client_rtmp_admin.dir/client_rtmp_admin.cpp.s
.PHONY : client_rtmp_admin.cpp.s

clienttest.o: clienttest.cpp.o

.PHONY : clienttest.o

# target to build an object file
clienttest.cpp.o:
	$(MAKE) -f CMakeFiles/client-put.dir/build.make CMakeFiles/client-put.dir/clienttest.cpp.o
.PHONY : clienttest.cpp.o

clienttest.i: clienttest.cpp.i

.PHONY : clienttest.i

# target to preprocess a source file
clienttest.cpp.i:
	$(MAKE) -f CMakeFiles/client-put.dir/build.make CMakeFiles/client-put.dir/clienttest.cpp.i
.PHONY : clienttest.cpp.i

clienttest.s: clienttest.cpp.s

.PHONY : clienttest.s

# target to generate assembly for a file
clienttest.cpp.s:
	$(MAKE) -f CMakeFiles/client-put.dir/build.make CMakeFiles/client-put.dir/clienttest.cpp.s
.PHONY : clienttest.cpp.s

db/MySQL.o: db/MySQL.cpp.o

.PHONY : db/MySQL.o

# target to build an object file
db/MySQL.cpp.o:
	$(MAKE) -f CMakeFiles/client_rtmp_admin.dir/build.make CMakeFiles/client_rtmp_admin.dir/db/MySQL.cpp.o
	$(MAKE) -f CMakeFiles/rtmp_cam_client.dir/build.make CMakeFiles/rtmp_cam_client.dir/db/MySQL.cpp.o
	$(MAKE) -f CMakeFiles/ForSUNSEV_IoTtest2.dir/build.make CMakeFiles/ForSUNSEV_IoTtest2.dir/db/MySQL.cpp.o
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/db/MySQL.cpp.o
	$(MAKE) -f CMakeFiles/client-put.dir/build.make CMakeFiles/client-put.dir/db/MySQL.cpp.o
	$(MAKE) -f CMakeFiles/client-get.dir/build.make CMakeFiles/client-get.dir/db/MySQL.cpp.o
	$(MAKE) -f CMakeFiles/client-normal.dir/build.make CMakeFiles/client-normal.dir/db/MySQL.cpp.o
.PHONY : db/MySQL.cpp.o

db/MySQL.i: db/MySQL.cpp.i

.PHONY : db/MySQL.i

# target to preprocess a source file
db/MySQL.cpp.i:
	$(MAKE) -f CMakeFiles/client_rtmp_admin.dir/build.make CMakeFiles/client_rtmp_admin.dir/db/MySQL.cpp.i
	$(MAKE) -f CMakeFiles/rtmp_cam_client.dir/build.make CMakeFiles/rtmp_cam_client.dir/db/MySQL.cpp.i
	$(MAKE) -f CMakeFiles/ForSUNSEV_IoTtest2.dir/build.make CMakeFiles/ForSUNSEV_IoTtest2.dir/db/MySQL.cpp.i
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/db/MySQL.cpp.i
	$(MAKE) -f CMakeFiles/client-put.dir/build.make CMakeFiles/client-put.dir/db/MySQL.cpp.i
	$(MAKE) -f CMakeFiles/client-get.dir/build.make CMakeFiles/client-get.dir/db/MySQL.cpp.i
	$(MAKE) -f CMakeFiles/client-normal.dir/build.make CMakeFiles/client-normal.dir/db/MySQL.cpp.i
.PHONY : db/MySQL.cpp.i

db/MySQL.s: db/MySQL.cpp.s

.PHONY : db/MySQL.s

# target to generate assembly for a file
db/MySQL.cpp.s:
	$(MAKE) -f CMakeFiles/client_rtmp_admin.dir/build.make CMakeFiles/client_rtmp_admin.dir/db/MySQL.cpp.s
	$(MAKE) -f CMakeFiles/rtmp_cam_client.dir/build.make CMakeFiles/rtmp_cam_client.dir/db/MySQL.cpp.s
	$(MAKE) -f CMakeFiles/ForSUNSEV_IoTtest2.dir/build.make CMakeFiles/ForSUNSEV_IoTtest2.dir/db/MySQL.cpp.s
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/db/MySQL.cpp.s
	$(MAKE) -f CMakeFiles/client-put.dir/build.make CMakeFiles/client-put.dir/db/MySQL.cpp.s
	$(MAKE) -f CMakeFiles/client-get.dir/build.make CMakeFiles/client-get.dir/db/MySQL.cpp.s
	$(MAKE) -f CMakeFiles/client-normal.dir/build.make CMakeFiles/client-normal.dir/db/MySQL.cpp.s
.PHONY : db/MySQL.cpp.s

ffmpeg/ForSUNSEV_IoT.o: ffmpeg/ForSUNSEV_IoT.cpp.o

.PHONY : ffmpeg/ForSUNSEV_IoT.o

# target to build an object file
ffmpeg/ForSUNSEV_IoT.cpp.o:
	$(MAKE) -f CMakeFiles/ForSUNSEV_IoTtest2.dir/build.make CMakeFiles/ForSUNSEV_IoTtest2.dir/ffmpeg/ForSUNSEV_IoT.cpp.o
.PHONY : ffmpeg/ForSUNSEV_IoT.cpp.o

ffmpeg/ForSUNSEV_IoT.i: ffmpeg/ForSUNSEV_IoT.cpp.i

.PHONY : ffmpeg/ForSUNSEV_IoT.i

# target to preprocess a source file
ffmpeg/ForSUNSEV_IoT.cpp.i:
	$(MAKE) -f CMakeFiles/ForSUNSEV_IoTtest2.dir/build.make CMakeFiles/ForSUNSEV_IoTtest2.dir/ffmpeg/ForSUNSEV_IoT.cpp.i
.PHONY : ffmpeg/ForSUNSEV_IoT.cpp.i

ffmpeg/ForSUNSEV_IoT.s: ffmpeg/ForSUNSEV_IoT.cpp.s

.PHONY : ffmpeg/ForSUNSEV_IoT.s

# target to generate assembly for a file
ffmpeg/ForSUNSEV_IoT.cpp.s:
	$(MAKE) -f CMakeFiles/ForSUNSEV_IoTtest2.dir/build.make CMakeFiles/ForSUNSEV_IoTtest2.dir/ffmpeg/ForSUNSEV_IoT.cpp.s
.PHONY : ffmpeg/ForSUNSEV_IoT.cpp.s

ffmpeg/RTMPParallel.o: ffmpeg/RTMPParallel.cpp.o

.PHONY : ffmpeg/RTMPParallel.o

# target to build an object file
ffmpeg/RTMPParallel.cpp.o:
	$(MAKE) -f CMakeFiles/client_rtmp_admin.dir/build.make CMakeFiles/client_rtmp_admin.dir/ffmpeg/RTMPParallel.cpp.o
	$(MAKE) -f CMakeFiles/rtmp_cam_client.dir/build.make CMakeFiles/rtmp_cam_client.dir/ffmpeg/RTMPParallel.cpp.o
	$(MAKE) -f CMakeFiles/ForSUNSEV_IoTtest2.dir/build.make CMakeFiles/ForSUNSEV_IoTtest2.dir/ffmpeg/RTMPParallel.cpp.o
.PHONY : ffmpeg/RTMPParallel.cpp.o

ffmpeg/RTMPParallel.i: ffmpeg/RTMPParallel.cpp.i

.PHONY : ffmpeg/RTMPParallel.i

# target to preprocess a source file
ffmpeg/RTMPParallel.cpp.i:
	$(MAKE) -f CMakeFiles/client_rtmp_admin.dir/build.make CMakeFiles/client_rtmp_admin.dir/ffmpeg/RTMPParallel.cpp.i
	$(MAKE) -f CMakeFiles/rtmp_cam_client.dir/build.make CMakeFiles/rtmp_cam_client.dir/ffmpeg/RTMPParallel.cpp.i
	$(MAKE) -f CMakeFiles/ForSUNSEV_IoTtest2.dir/build.make CMakeFiles/ForSUNSEV_IoTtest2.dir/ffmpeg/RTMPParallel.cpp.i
.PHONY : ffmpeg/RTMPParallel.cpp.i

ffmpeg/RTMPParallel.s: ffmpeg/RTMPParallel.cpp.s

.PHONY : ffmpeg/RTMPParallel.s

# target to generate assembly for a file
ffmpeg/RTMPParallel.cpp.s:
	$(MAKE) -f CMakeFiles/client_rtmp_admin.dir/build.make CMakeFiles/client_rtmp_admin.dir/ffmpeg/RTMPParallel.cpp.s
	$(MAKE) -f CMakeFiles/rtmp_cam_client.dir/build.make CMakeFiles/rtmp_cam_client.dir/ffmpeg/RTMPParallel.cpp.s
	$(MAKE) -f CMakeFiles/ForSUNSEV_IoTtest2.dir/build.make CMakeFiles/ForSUNSEV_IoTtest2.dir/ffmpeg/RTMPParallel.cpp.s
.PHONY : ffmpeg/RTMPParallel.cpp.s

ipfs/IPFSCtrl.o: ipfs/IPFSCtrl.cpp.o

.PHONY : ipfs/IPFSCtrl.o

# target to build an object file
ipfs/IPFSCtrl.cpp.o:
	$(MAKE) -f CMakeFiles/client_rtmp_admin.dir/build.make CMakeFiles/client_rtmp_admin.dir/ipfs/IPFSCtrl.cpp.o
	$(MAKE) -f CMakeFiles/rtmp_cam_client.dir/build.make CMakeFiles/rtmp_cam_client.dir/ipfs/IPFSCtrl.cpp.o
	$(MAKE) -f CMakeFiles/ForSUNSEV_IoTtest2.dir/build.make CMakeFiles/ForSUNSEV_IoTtest2.dir/ipfs/IPFSCtrl.cpp.o
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/ipfs/IPFSCtrl.cpp.o
	$(MAKE) -f CMakeFiles/client-put.dir/build.make CMakeFiles/client-put.dir/ipfs/IPFSCtrl.cpp.o
	$(MAKE) -f CMakeFiles/client-get.dir/build.make CMakeFiles/client-get.dir/ipfs/IPFSCtrl.cpp.o
	$(MAKE) -f CMakeFiles/client-normal.dir/build.make CMakeFiles/client-normal.dir/ipfs/IPFSCtrl.cpp.o
.PHONY : ipfs/IPFSCtrl.cpp.o

ipfs/IPFSCtrl.i: ipfs/IPFSCtrl.cpp.i

.PHONY : ipfs/IPFSCtrl.i

# target to preprocess a source file
ipfs/IPFSCtrl.cpp.i:
	$(MAKE) -f CMakeFiles/client_rtmp_admin.dir/build.make CMakeFiles/client_rtmp_admin.dir/ipfs/IPFSCtrl.cpp.i
	$(MAKE) -f CMakeFiles/rtmp_cam_client.dir/build.make CMakeFiles/rtmp_cam_client.dir/ipfs/IPFSCtrl.cpp.i
	$(MAKE) -f CMakeFiles/ForSUNSEV_IoTtest2.dir/build.make CMakeFiles/ForSUNSEV_IoTtest2.dir/ipfs/IPFSCtrl.cpp.i
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/ipfs/IPFSCtrl.cpp.i
	$(MAKE) -f CMakeFiles/client-put.dir/build.make CMakeFiles/client-put.dir/ipfs/IPFSCtrl.cpp.i
	$(MAKE) -f CMakeFiles/client-get.dir/build.make CMakeFiles/client-get.dir/ipfs/IPFSCtrl.cpp.i
	$(MAKE) -f CMakeFiles/client-normal.dir/build.make CMakeFiles/client-normal.dir/ipfs/IPFSCtrl.cpp.i
.PHONY : ipfs/IPFSCtrl.cpp.i

ipfs/IPFSCtrl.s: ipfs/IPFSCtrl.cpp.s

.PHONY : ipfs/IPFSCtrl.s

# target to generate assembly for a file
ipfs/IPFSCtrl.cpp.s:
	$(MAKE) -f CMakeFiles/client_rtmp_admin.dir/build.make CMakeFiles/client_rtmp_admin.dir/ipfs/IPFSCtrl.cpp.s
	$(MAKE) -f CMakeFiles/rtmp_cam_client.dir/build.make CMakeFiles/rtmp_cam_client.dir/ipfs/IPFSCtrl.cpp.s
	$(MAKE) -f CMakeFiles/ForSUNSEV_IoTtest2.dir/build.make CMakeFiles/ForSUNSEV_IoTtest2.dir/ipfs/IPFSCtrl.cpp.s
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/ipfs/IPFSCtrl.cpp.s
	$(MAKE) -f CMakeFiles/client-put.dir/build.make CMakeFiles/client-put.dir/ipfs/IPFSCtrl.cpp.s
	$(MAKE) -f CMakeFiles/client-get.dir/build.make CMakeFiles/client-get.dir/ipfs/IPFSCtrl.cpp.s
	$(MAKE) -f CMakeFiles/client-normal.dir/build.make CMakeFiles/client-normal.dir/ipfs/IPFSCtrl.cpp.s
.PHONY : ipfs/IPFSCtrl.cpp.s

json/MsgFFmpeg.o: json/MsgFFmpeg.cpp.o

.PHONY : json/MsgFFmpeg.o

# target to build an object file
json/MsgFFmpeg.cpp.o:
	$(MAKE) -f CMakeFiles/client_rtmp_admin.dir/build.make CMakeFiles/client_rtmp_admin.dir/json/MsgFFmpeg.cpp.o
	$(MAKE) -f CMakeFiles/rtmp_cam_client.dir/build.make CMakeFiles/rtmp_cam_client.dir/json/MsgFFmpeg.cpp.o
	$(MAKE) -f CMakeFiles/ForSUNSEV_IoTtest2.dir/build.make CMakeFiles/ForSUNSEV_IoTtest2.dir/json/MsgFFmpeg.cpp.o
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/json/MsgFFmpeg.cpp.o
	$(MAKE) -f CMakeFiles/client-put.dir/build.make CMakeFiles/client-put.dir/json/MsgFFmpeg.cpp.o
	$(MAKE) -f CMakeFiles/client-get.dir/build.make CMakeFiles/client-get.dir/json/MsgFFmpeg.cpp.o
	$(MAKE) -f CMakeFiles/client-normal.dir/build.make CMakeFiles/client-normal.dir/json/MsgFFmpeg.cpp.o
.PHONY : json/MsgFFmpeg.cpp.o

json/MsgFFmpeg.i: json/MsgFFmpeg.cpp.i

.PHONY : json/MsgFFmpeg.i

# target to preprocess a source file
json/MsgFFmpeg.cpp.i:
	$(MAKE) -f CMakeFiles/client_rtmp_admin.dir/build.make CMakeFiles/client_rtmp_admin.dir/json/MsgFFmpeg.cpp.i
	$(MAKE) -f CMakeFiles/rtmp_cam_client.dir/build.make CMakeFiles/rtmp_cam_client.dir/json/MsgFFmpeg.cpp.i
	$(MAKE) -f CMakeFiles/ForSUNSEV_IoTtest2.dir/build.make CMakeFiles/ForSUNSEV_IoTtest2.dir/json/MsgFFmpeg.cpp.i
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/json/MsgFFmpeg.cpp.i
	$(MAKE) -f CMakeFiles/client-put.dir/build.make CMakeFiles/client-put.dir/json/MsgFFmpeg.cpp.i
	$(MAKE) -f CMakeFiles/client-get.dir/build.make CMakeFiles/client-get.dir/json/MsgFFmpeg.cpp.i
	$(MAKE) -f CMakeFiles/client-normal.dir/build.make CMakeFiles/client-normal.dir/json/MsgFFmpeg.cpp.i
.PHONY : json/MsgFFmpeg.cpp.i

json/MsgFFmpeg.s: json/MsgFFmpeg.cpp.s

.PHONY : json/MsgFFmpeg.s

# target to generate assembly for a file
json/MsgFFmpeg.cpp.s:
	$(MAKE) -f CMakeFiles/client_rtmp_admin.dir/build.make CMakeFiles/client_rtmp_admin.dir/json/MsgFFmpeg.cpp.s
	$(MAKE) -f CMakeFiles/rtmp_cam_client.dir/build.make CMakeFiles/rtmp_cam_client.dir/json/MsgFFmpeg.cpp.s
	$(MAKE) -f CMakeFiles/ForSUNSEV_IoTtest2.dir/build.make CMakeFiles/ForSUNSEV_IoTtest2.dir/json/MsgFFmpeg.cpp.s
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/json/MsgFFmpeg.cpp.s
	$(MAKE) -f CMakeFiles/client-put.dir/build.make CMakeFiles/client-put.dir/json/MsgFFmpeg.cpp.s
	$(MAKE) -f CMakeFiles/client-get.dir/build.make CMakeFiles/client-get.dir/json/MsgFFmpeg.cpp.s
	$(MAKE) -f CMakeFiles/client-normal.dir/build.make CMakeFiles/client-normal.dir/json/MsgFFmpeg.cpp.s
.PHONY : json/MsgFFmpeg.cpp.s

json/MsgIPFS.o: json/MsgIPFS.cpp.o

.PHONY : json/MsgIPFS.o

# target to build an object file
json/MsgIPFS.cpp.o:
	$(MAKE) -f CMakeFiles/client_rtmp_admin.dir/build.make CMakeFiles/client_rtmp_admin.dir/json/MsgIPFS.cpp.o
	$(MAKE) -f CMakeFiles/rtmp_cam_client.dir/build.make CMakeFiles/rtmp_cam_client.dir/json/MsgIPFS.cpp.o
	$(MAKE) -f CMakeFiles/ForSUNSEV_IoTtest2.dir/build.make CMakeFiles/ForSUNSEV_IoTtest2.dir/json/MsgIPFS.cpp.o
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/json/MsgIPFS.cpp.o
	$(MAKE) -f CMakeFiles/client-put.dir/build.make CMakeFiles/client-put.dir/json/MsgIPFS.cpp.o
	$(MAKE) -f CMakeFiles/client-get.dir/build.make CMakeFiles/client-get.dir/json/MsgIPFS.cpp.o
	$(MAKE) -f CMakeFiles/client-normal.dir/build.make CMakeFiles/client-normal.dir/json/MsgIPFS.cpp.o
.PHONY : json/MsgIPFS.cpp.o

json/MsgIPFS.i: json/MsgIPFS.cpp.i

.PHONY : json/MsgIPFS.i

# target to preprocess a source file
json/MsgIPFS.cpp.i:
	$(MAKE) -f CMakeFiles/client_rtmp_admin.dir/build.make CMakeFiles/client_rtmp_admin.dir/json/MsgIPFS.cpp.i
	$(MAKE) -f CMakeFiles/rtmp_cam_client.dir/build.make CMakeFiles/rtmp_cam_client.dir/json/MsgIPFS.cpp.i
	$(MAKE) -f CMakeFiles/ForSUNSEV_IoTtest2.dir/build.make CMakeFiles/ForSUNSEV_IoTtest2.dir/json/MsgIPFS.cpp.i
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/json/MsgIPFS.cpp.i
	$(MAKE) -f CMakeFiles/client-put.dir/build.make CMakeFiles/client-put.dir/json/MsgIPFS.cpp.i
	$(MAKE) -f CMakeFiles/client-get.dir/build.make CMakeFiles/client-get.dir/json/MsgIPFS.cpp.i
	$(MAKE) -f CMakeFiles/client-normal.dir/build.make CMakeFiles/client-normal.dir/json/MsgIPFS.cpp.i
.PHONY : json/MsgIPFS.cpp.i

json/MsgIPFS.s: json/MsgIPFS.cpp.s

.PHONY : json/MsgIPFS.s

# target to generate assembly for a file
json/MsgIPFS.cpp.s:
	$(MAKE) -f CMakeFiles/client_rtmp_admin.dir/build.make CMakeFiles/client_rtmp_admin.dir/json/MsgIPFS.cpp.s
	$(MAKE) -f CMakeFiles/rtmp_cam_client.dir/build.make CMakeFiles/rtmp_cam_client.dir/json/MsgIPFS.cpp.s
	$(MAKE) -f CMakeFiles/ForSUNSEV_IoTtest2.dir/build.make CMakeFiles/ForSUNSEV_IoTtest2.dir/json/MsgIPFS.cpp.s
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/json/MsgIPFS.cpp.s
	$(MAKE) -f CMakeFiles/client-put.dir/build.make CMakeFiles/client-put.dir/json/MsgIPFS.cpp.s
	$(MAKE) -f CMakeFiles/client-get.dir/build.make CMakeFiles/client-get.dir/json/MsgIPFS.cpp.s
	$(MAKE) -f CMakeFiles/client-normal.dir/build.make CMakeFiles/client-normal.dir/json/MsgIPFS.cpp.s
.PHONY : json/MsgIPFS.cpp.s

json/MsgMove.o: json/MsgMove.cpp.o

.PHONY : json/MsgMove.o

# target to build an object file
json/MsgMove.cpp.o:
	$(MAKE) -f CMakeFiles/client_rtmp_admin.dir/build.make CMakeFiles/client_rtmp_admin.dir/json/MsgMove.cpp.o
	$(MAKE) -f CMakeFiles/rtmp_cam_client.dir/build.make CMakeFiles/rtmp_cam_client.dir/json/MsgMove.cpp.o
	$(MAKE) -f CMakeFiles/ForSUNSEV_IoTtest2.dir/build.make CMakeFiles/ForSUNSEV_IoTtest2.dir/json/MsgMove.cpp.o
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/json/MsgMove.cpp.o
	$(MAKE) -f CMakeFiles/client-put.dir/build.make CMakeFiles/client-put.dir/json/MsgMove.cpp.o
	$(MAKE) -f CMakeFiles/client-get.dir/build.make CMakeFiles/client-get.dir/json/MsgMove.cpp.o
	$(MAKE) -f CMakeFiles/client-normal.dir/build.make CMakeFiles/client-normal.dir/json/MsgMove.cpp.o
.PHONY : json/MsgMove.cpp.o

json/MsgMove.i: json/MsgMove.cpp.i

.PHONY : json/MsgMove.i

# target to preprocess a source file
json/MsgMove.cpp.i:
	$(MAKE) -f CMakeFiles/client_rtmp_admin.dir/build.make CMakeFiles/client_rtmp_admin.dir/json/MsgMove.cpp.i
	$(MAKE) -f CMakeFiles/rtmp_cam_client.dir/build.make CMakeFiles/rtmp_cam_client.dir/json/MsgMove.cpp.i
	$(MAKE) -f CMakeFiles/ForSUNSEV_IoTtest2.dir/build.make CMakeFiles/ForSUNSEV_IoTtest2.dir/json/MsgMove.cpp.i
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/json/MsgMove.cpp.i
	$(MAKE) -f CMakeFiles/client-put.dir/build.make CMakeFiles/client-put.dir/json/MsgMove.cpp.i
	$(MAKE) -f CMakeFiles/client-get.dir/build.make CMakeFiles/client-get.dir/json/MsgMove.cpp.i
	$(MAKE) -f CMakeFiles/client-normal.dir/build.make CMakeFiles/client-normal.dir/json/MsgMove.cpp.i
.PHONY : json/MsgMove.cpp.i

json/MsgMove.s: json/MsgMove.cpp.s

.PHONY : json/MsgMove.s

# target to generate assembly for a file
json/MsgMove.cpp.s:
	$(MAKE) -f CMakeFiles/client_rtmp_admin.dir/build.make CMakeFiles/client_rtmp_admin.dir/json/MsgMove.cpp.s
	$(MAKE) -f CMakeFiles/rtmp_cam_client.dir/build.make CMakeFiles/rtmp_cam_client.dir/json/MsgMove.cpp.s
	$(MAKE) -f CMakeFiles/ForSUNSEV_IoTtest2.dir/build.make CMakeFiles/ForSUNSEV_IoTtest2.dir/json/MsgMove.cpp.s
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/json/MsgMove.cpp.s
	$(MAKE) -f CMakeFiles/client-put.dir/build.make CMakeFiles/client-put.dir/json/MsgMove.cpp.s
	$(MAKE) -f CMakeFiles/client-get.dir/build.make CMakeFiles/client-get.dir/json/MsgMove.cpp.s
	$(MAKE) -f CMakeFiles/client-normal.dir/build.make CMakeFiles/client-normal.dir/json/MsgMove.cpp.s
.PHONY : json/MsgMove.cpp.s

logic/MsgHandler.o: logic/MsgHandler.cpp.o

.PHONY : logic/MsgHandler.o

# target to build an object file
logic/MsgHandler.cpp.o:
	$(MAKE) -f CMakeFiles/client_rtmp_admin.dir/build.make CMakeFiles/client_rtmp_admin.dir/logic/MsgHandler.cpp.o
	$(MAKE) -f CMakeFiles/rtmp_cam_client.dir/build.make CMakeFiles/rtmp_cam_client.dir/logic/MsgHandler.cpp.o
	$(MAKE) -f CMakeFiles/ForSUNSEV_IoTtest2.dir/build.make CMakeFiles/ForSUNSEV_IoTtest2.dir/logic/MsgHandler.cpp.o
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/logic/MsgHandler.cpp.o
	$(MAKE) -f CMakeFiles/client-put.dir/build.make CMakeFiles/client-put.dir/logic/MsgHandler.cpp.o
	$(MAKE) -f CMakeFiles/client-get.dir/build.make CMakeFiles/client-get.dir/logic/MsgHandler.cpp.o
	$(MAKE) -f CMakeFiles/client-normal.dir/build.make CMakeFiles/client-normal.dir/logic/MsgHandler.cpp.o
.PHONY : logic/MsgHandler.cpp.o

logic/MsgHandler.i: logic/MsgHandler.cpp.i

.PHONY : logic/MsgHandler.i

# target to preprocess a source file
logic/MsgHandler.cpp.i:
	$(MAKE) -f CMakeFiles/client_rtmp_admin.dir/build.make CMakeFiles/client_rtmp_admin.dir/logic/MsgHandler.cpp.i
	$(MAKE) -f CMakeFiles/rtmp_cam_client.dir/build.make CMakeFiles/rtmp_cam_client.dir/logic/MsgHandler.cpp.i
	$(MAKE) -f CMakeFiles/ForSUNSEV_IoTtest2.dir/build.make CMakeFiles/ForSUNSEV_IoTtest2.dir/logic/MsgHandler.cpp.i
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/logic/MsgHandler.cpp.i
	$(MAKE) -f CMakeFiles/client-put.dir/build.make CMakeFiles/client-put.dir/logic/MsgHandler.cpp.i
	$(MAKE) -f CMakeFiles/client-get.dir/build.make CMakeFiles/client-get.dir/logic/MsgHandler.cpp.i
	$(MAKE) -f CMakeFiles/client-normal.dir/build.make CMakeFiles/client-normal.dir/logic/MsgHandler.cpp.i
.PHONY : logic/MsgHandler.cpp.i

logic/MsgHandler.s: logic/MsgHandler.cpp.s

.PHONY : logic/MsgHandler.s

# target to generate assembly for a file
logic/MsgHandler.cpp.s:
	$(MAKE) -f CMakeFiles/client_rtmp_admin.dir/build.make CMakeFiles/client_rtmp_admin.dir/logic/MsgHandler.cpp.s
	$(MAKE) -f CMakeFiles/rtmp_cam_client.dir/build.make CMakeFiles/rtmp_cam_client.dir/logic/MsgHandler.cpp.s
	$(MAKE) -f CMakeFiles/ForSUNSEV_IoTtest2.dir/build.make CMakeFiles/ForSUNSEV_IoTtest2.dir/logic/MsgHandler.cpp.s
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/logic/MsgHandler.cpp.s
	$(MAKE) -f CMakeFiles/client-put.dir/build.make CMakeFiles/client-put.dir/logic/MsgHandler.cpp.s
	$(MAKE) -f CMakeFiles/client-get.dir/build.make CMakeFiles/client-get.dir/logic/MsgHandler.cpp.s
	$(MAKE) -f CMakeFiles/client-normal.dir/build.make CMakeFiles/client-normal.dir/logic/MsgHandler.cpp.s
.PHONY : logic/MsgHandler.cpp.s

net/ByteArray.o: net/ByteArray.cpp.o

.PHONY : net/ByteArray.o

# target to build an object file
net/ByteArray.cpp.o:
	$(MAKE) -f CMakeFiles/client_rtmp_admin.dir/build.make CMakeFiles/client_rtmp_admin.dir/net/ByteArray.cpp.o
	$(MAKE) -f CMakeFiles/rtmp_cam_client.dir/build.make CMakeFiles/rtmp_cam_client.dir/net/ByteArray.cpp.o
	$(MAKE) -f CMakeFiles/ForSUNSEV_IoTtest2.dir/build.make CMakeFiles/ForSUNSEV_IoTtest2.dir/net/ByteArray.cpp.o
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/net/ByteArray.cpp.o
	$(MAKE) -f CMakeFiles/client-put.dir/build.make CMakeFiles/client-put.dir/net/ByteArray.cpp.o
	$(MAKE) -f CMakeFiles/client-get.dir/build.make CMakeFiles/client-get.dir/net/ByteArray.cpp.o
	$(MAKE) -f CMakeFiles/client-normal.dir/build.make CMakeFiles/client-normal.dir/net/ByteArray.cpp.o
.PHONY : net/ByteArray.cpp.o

net/ByteArray.i: net/ByteArray.cpp.i

.PHONY : net/ByteArray.i

# target to preprocess a source file
net/ByteArray.cpp.i:
	$(MAKE) -f CMakeFiles/client_rtmp_admin.dir/build.make CMakeFiles/client_rtmp_admin.dir/net/ByteArray.cpp.i
	$(MAKE) -f CMakeFiles/rtmp_cam_client.dir/build.make CMakeFiles/rtmp_cam_client.dir/net/ByteArray.cpp.i
	$(MAKE) -f CMakeFiles/ForSUNSEV_IoTtest2.dir/build.make CMakeFiles/ForSUNSEV_IoTtest2.dir/net/ByteArray.cpp.i
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/net/ByteArray.cpp.i
	$(MAKE) -f CMakeFiles/client-put.dir/build.make CMakeFiles/client-put.dir/net/ByteArray.cpp.i
	$(MAKE) -f CMakeFiles/client-get.dir/build.make CMakeFiles/client-get.dir/net/ByteArray.cpp.i
	$(MAKE) -f CMakeFiles/client-normal.dir/build.make CMakeFiles/client-normal.dir/net/ByteArray.cpp.i
.PHONY : net/ByteArray.cpp.i

net/ByteArray.s: net/ByteArray.cpp.s

.PHONY : net/ByteArray.s

# target to generate assembly for a file
net/ByteArray.cpp.s:
	$(MAKE) -f CMakeFiles/client_rtmp_admin.dir/build.make CMakeFiles/client_rtmp_admin.dir/net/ByteArray.cpp.s
	$(MAKE) -f CMakeFiles/rtmp_cam_client.dir/build.make CMakeFiles/rtmp_cam_client.dir/net/ByteArray.cpp.s
	$(MAKE) -f CMakeFiles/ForSUNSEV_IoTtest2.dir/build.make CMakeFiles/ForSUNSEV_IoTtest2.dir/net/ByteArray.cpp.s
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/net/ByteArray.cpp.s
	$(MAKE) -f CMakeFiles/client-put.dir/build.make CMakeFiles/client-put.dir/net/ByteArray.cpp.s
	$(MAKE) -f CMakeFiles/client-get.dir/build.make CMakeFiles/client-get.dir/net/ByteArray.cpp.s
	$(MAKE) -f CMakeFiles/client-normal.dir/build.make CMakeFiles/client-normal.dir/net/ByteArray.cpp.s
.PHONY : net/ByteArray.cpp.s

net/CJsonObject.o: net/CJsonObject.cpp.o

.PHONY : net/CJsonObject.o

# target to build an object file
net/CJsonObject.cpp.o:
	$(MAKE) -f CMakeFiles/client_rtmp_admin.dir/build.make CMakeFiles/client_rtmp_admin.dir/net/CJsonObject.cpp.o
	$(MAKE) -f CMakeFiles/rtmp_cam_client.dir/build.make CMakeFiles/rtmp_cam_client.dir/net/CJsonObject.cpp.o
	$(MAKE) -f CMakeFiles/ForSUNSEV_IoTtest2.dir/build.make CMakeFiles/ForSUNSEV_IoTtest2.dir/net/CJsonObject.cpp.o
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/net/CJsonObject.cpp.o
	$(MAKE) -f CMakeFiles/client-put.dir/build.make CMakeFiles/client-put.dir/net/CJsonObject.cpp.o
	$(MAKE) -f CMakeFiles/client-get.dir/build.make CMakeFiles/client-get.dir/net/CJsonObject.cpp.o
	$(MAKE) -f CMakeFiles/client-normal.dir/build.make CMakeFiles/client-normal.dir/net/CJsonObject.cpp.o
.PHONY : net/CJsonObject.cpp.o

net/CJsonObject.i: net/CJsonObject.cpp.i

.PHONY : net/CJsonObject.i

# target to preprocess a source file
net/CJsonObject.cpp.i:
	$(MAKE) -f CMakeFiles/client_rtmp_admin.dir/build.make CMakeFiles/client_rtmp_admin.dir/net/CJsonObject.cpp.i
	$(MAKE) -f CMakeFiles/rtmp_cam_client.dir/build.make CMakeFiles/rtmp_cam_client.dir/net/CJsonObject.cpp.i
	$(MAKE) -f CMakeFiles/ForSUNSEV_IoTtest2.dir/build.make CMakeFiles/ForSUNSEV_IoTtest2.dir/net/CJsonObject.cpp.i
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/net/CJsonObject.cpp.i
	$(MAKE) -f CMakeFiles/client-put.dir/build.make CMakeFiles/client-put.dir/net/CJsonObject.cpp.i
	$(MAKE) -f CMakeFiles/client-get.dir/build.make CMakeFiles/client-get.dir/net/CJsonObject.cpp.i
	$(MAKE) -f CMakeFiles/client-normal.dir/build.make CMakeFiles/client-normal.dir/net/CJsonObject.cpp.i
.PHONY : net/CJsonObject.cpp.i

net/CJsonObject.s: net/CJsonObject.cpp.s

.PHONY : net/CJsonObject.s

# target to generate assembly for a file
net/CJsonObject.cpp.s:
	$(MAKE) -f CMakeFiles/client_rtmp_admin.dir/build.make CMakeFiles/client_rtmp_admin.dir/net/CJsonObject.cpp.s
	$(MAKE) -f CMakeFiles/rtmp_cam_client.dir/build.make CMakeFiles/rtmp_cam_client.dir/net/CJsonObject.cpp.s
	$(MAKE) -f CMakeFiles/ForSUNSEV_IoTtest2.dir/build.make CMakeFiles/ForSUNSEV_IoTtest2.dir/net/CJsonObject.cpp.s
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/net/CJsonObject.cpp.s
	$(MAKE) -f CMakeFiles/client-put.dir/build.make CMakeFiles/client-put.dir/net/CJsonObject.cpp.s
	$(MAKE) -f CMakeFiles/client-get.dir/build.make CMakeFiles/client-get.dir/net/CJsonObject.cpp.s
	$(MAKE) -f CMakeFiles/client-normal.dir/build.make CMakeFiles/client-normal.dir/net/CJsonObject.cpp.s
.PHONY : net/CJsonObject.cpp.s

net/ClientState.o: net/ClientState.cpp.o

.PHONY : net/ClientState.o

# target to build an object file
net/ClientState.cpp.o:
	$(MAKE) -f CMakeFiles/client_rtmp_admin.dir/build.make CMakeFiles/client_rtmp_admin.dir/net/ClientState.cpp.o
	$(MAKE) -f CMakeFiles/rtmp_cam_client.dir/build.make CMakeFiles/rtmp_cam_client.dir/net/ClientState.cpp.o
	$(MAKE) -f CMakeFiles/ForSUNSEV_IoTtest2.dir/build.make CMakeFiles/ForSUNSEV_IoTtest2.dir/net/ClientState.cpp.o
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/net/ClientState.cpp.o
	$(MAKE) -f CMakeFiles/client-put.dir/build.make CMakeFiles/client-put.dir/net/ClientState.cpp.o
	$(MAKE) -f CMakeFiles/client-get.dir/build.make CMakeFiles/client-get.dir/net/ClientState.cpp.o
	$(MAKE) -f CMakeFiles/client-normal.dir/build.make CMakeFiles/client-normal.dir/net/ClientState.cpp.o
.PHONY : net/ClientState.cpp.o

net/ClientState.i: net/ClientState.cpp.i

.PHONY : net/ClientState.i

# target to preprocess a source file
net/ClientState.cpp.i:
	$(MAKE) -f CMakeFiles/client_rtmp_admin.dir/build.make CMakeFiles/client_rtmp_admin.dir/net/ClientState.cpp.i
	$(MAKE) -f CMakeFiles/rtmp_cam_client.dir/build.make CMakeFiles/rtmp_cam_client.dir/net/ClientState.cpp.i
	$(MAKE) -f CMakeFiles/ForSUNSEV_IoTtest2.dir/build.make CMakeFiles/ForSUNSEV_IoTtest2.dir/net/ClientState.cpp.i
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/net/ClientState.cpp.i
	$(MAKE) -f CMakeFiles/client-put.dir/build.make CMakeFiles/client-put.dir/net/ClientState.cpp.i
	$(MAKE) -f CMakeFiles/client-get.dir/build.make CMakeFiles/client-get.dir/net/ClientState.cpp.i
	$(MAKE) -f CMakeFiles/client-normal.dir/build.make CMakeFiles/client-normal.dir/net/ClientState.cpp.i
.PHONY : net/ClientState.cpp.i

net/ClientState.s: net/ClientState.cpp.s

.PHONY : net/ClientState.s

# target to generate assembly for a file
net/ClientState.cpp.s:
	$(MAKE) -f CMakeFiles/client_rtmp_admin.dir/build.make CMakeFiles/client_rtmp_admin.dir/net/ClientState.cpp.s
	$(MAKE) -f CMakeFiles/rtmp_cam_client.dir/build.make CMakeFiles/rtmp_cam_client.dir/net/ClientState.cpp.s
	$(MAKE) -f CMakeFiles/ForSUNSEV_IoTtest2.dir/build.make CMakeFiles/ForSUNSEV_IoTtest2.dir/net/ClientState.cpp.s
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/net/ClientState.cpp.s
	$(MAKE) -f CMakeFiles/client-put.dir/build.make CMakeFiles/client-put.dir/net/ClientState.cpp.s
	$(MAKE) -f CMakeFiles/client-get.dir/build.make CMakeFiles/client-get.dir/net/ClientState.cpp.s
	$(MAKE) -f CMakeFiles/client-normal.dir/build.make CMakeFiles/client-normal.dir/net/ClientState.cpp.s
.PHONY : net/ClientState.cpp.s

net/MsgBase.o: net/MsgBase.cpp.o

.PHONY : net/MsgBase.o

# target to build an object file
net/MsgBase.cpp.o:
	$(MAKE) -f CMakeFiles/client_rtmp_admin.dir/build.make CMakeFiles/client_rtmp_admin.dir/net/MsgBase.cpp.o
	$(MAKE) -f CMakeFiles/rtmp_cam_client.dir/build.make CMakeFiles/rtmp_cam_client.dir/net/MsgBase.cpp.o
	$(MAKE) -f CMakeFiles/ForSUNSEV_IoTtest2.dir/build.make CMakeFiles/ForSUNSEV_IoTtest2.dir/net/MsgBase.cpp.o
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/net/MsgBase.cpp.o
	$(MAKE) -f CMakeFiles/client-put.dir/build.make CMakeFiles/client-put.dir/net/MsgBase.cpp.o
	$(MAKE) -f CMakeFiles/client-get.dir/build.make CMakeFiles/client-get.dir/net/MsgBase.cpp.o
	$(MAKE) -f CMakeFiles/client-normal.dir/build.make CMakeFiles/client-normal.dir/net/MsgBase.cpp.o
.PHONY : net/MsgBase.cpp.o

net/MsgBase.i: net/MsgBase.cpp.i

.PHONY : net/MsgBase.i

# target to preprocess a source file
net/MsgBase.cpp.i:
	$(MAKE) -f CMakeFiles/client_rtmp_admin.dir/build.make CMakeFiles/client_rtmp_admin.dir/net/MsgBase.cpp.i
	$(MAKE) -f CMakeFiles/rtmp_cam_client.dir/build.make CMakeFiles/rtmp_cam_client.dir/net/MsgBase.cpp.i
	$(MAKE) -f CMakeFiles/ForSUNSEV_IoTtest2.dir/build.make CMakeFiles/ForSUNSEV_IoTtest2.dir/net/MsgBase.cpp.i
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/net/MsgBase.cpp.i
	$(MAKE) -f CMakeFiles/client-put.dir/build.make CMakeFiles/client-put.dir/net/MsgBase.cpp.i
	$(MAKE) -f CMakeFiles/client-get.dir/build.make CMakeFiles/client-get.dir/net/MsgBase.cpp.i
	$(MAKE) -f CMakeFiles/client-normal.dir/build.make CMakeFiles/client-normal.dir/net/MsgBase.cpp.i
.PHONY : net/MsgBase.cpp.i

net/MsgBase.s: net/MsgBase.cpp.s

.PHONY : net/MsgBase.s

# target to generate assembly for a file
net/MsgBase.cpp.s:
	$(MAKE) -f CMakeFiles/client_rtmp_admin.dir/build.make CMakeFiles/client_rtmp_admin.dir/net/MsgBase.cpp.s
	$(MAKE) -f CMakeFiles/rtmp_cam_client.dir/build.make CMakeFiles/rtmp_cam_client.dir/net/MsgBase.cpp.s
	$(MAKE) -f CMakeFiles/ForSUNSEV_IoTtest2.dir/build.make CMakeFiles/ForSUNSEV_IoTtest2.dir/net/MsgBase.cpp.s
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/net/MsgBase.cpp.s
	$(MAKE) -f CMakeFiles/client-put.dir/build.make CMakeFiles/client-put.dir/net/MsgBase.cpp.s
	$(MAKE) -f CMakeFiles/client-get.dir/build.make CMakeFiles/client-get.dir/net/MsgBase.cpp.s
	$(MAKE) -f CMakeFiles/client-normal.dir/build.make CMakeFiles/client-normal.dir/net/MsgBase.cpp.s
.PHONY : net/MsgBase.cpp.s

net/NetManager.o: net/NetManager.cpp.o

.PHONY : net/NetManager.o

# target to build an object file
net/NetManager.cpp.o:
	$(MAKE) -f CMakeFiles/client_rtmp_admin.dir/build.make CMakeFiles/client_rtmp_admin.dir/net/NetManager.cpp.o
	$(MAKE) -f CMakeFiles/rtmp_cam_client.dir/build.make CMakeFiles/rtmp_cam_client.dir/net/NetManager.cpp.o
	$(MAKE) -f CMakeFiles/ForSUNSEV_IoTtest2.dir/build.make CMakeFiles/ForSUNSEV_IoTtest2.dir/net/NetManager.cpp.o
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/net/NetManager.cpp.o
	$(MAKE) -f CMakeFiles/client-put.dir/build.make CMakeFiles/client-put.dir/net/NetManager.cpp.o
	$(MAKE) -f CMakeFiles/client-get.dir/build.make CMakeFiles/client-get.dir/net/NetManager.cpp.o
	$(MAKE) -f CMakeFiles/client-normal.dir/build.make CMakeFiles/client-normal.dir/net/NetManager.cpp.o
.PHONY : net/NetManager.cpp.o

net/NetManager.i: net/NetManager.cpp.i

.PHONY : net/NetManager.i

# target to preprocess a source file
net/NetManager.cpp.i:
	$(MAKE) -f CMakeFiles/client_rtmp_admin.dir/build.make CMakeFiles/client_rtmp_admin.dir/net/NetManager.cpp.i
	$(MAKE) -f CMakeFiles/rtmp_cam_client.dir/build.make CMakeFiles/rtmp_cam_client.dir/net/NetManager.cpp.i
	$(MAKE) -f CMakeFiles/ForSUNSEV_IoTtest2.dir/build.make CMakeFiles/ForSUNSEV_IoTtest2.dir/net/NetManager.cpp.i
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/net/NetManager.cpp.i
	$(MAKE) -f CMakeFiles/client-put.dir/build.make CMakeFiles/client-put.dir/net/NetManager.cpp.i
	$(MAKE) -f CMakeFiles/client-get.dir/build.make CMakeFiles/client-get.dir/net/NetManager.cpp.i
	$(MAKE) -f CMakeFiles/client-normal.dir/build.make CMakeFiles/client-normal.dir/net/NetManager.cpp.i
.PHONY : net/NetManager.cpp.i

net/NetManager.s: net/NetManager.cpp.s

.PHONY : net/NetManager.s

# target to generate assembly for a file
net/NetManager.cpp.s:
	$(MAKE) -f CMakeFiles/client_rtmp_admin.dir/build.make CMakeFiles/client_rtmp_admin.dir/net/NetManager.cpp.s
	$(MAKE) -f CMakeFiles/rtmp_cam_client.dir/build.make CMakeFiles/rtmp_cam_client.dir/net/NetManager.cpp.s
	$(MAKE) -f CMakeFiles/ForSUNSEV_IoTtest2.dir/build.make CMakeFiles/ForSUNSEV_IoTtest2.dir/net/NetManager.cpp.s
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/net/NetManager.cpp.s
	$(MAKE) -f CMakeFiles/client-put.dir/build.make CMakeFiles/client-put.dir/net/NetManager.cpp.s
	$(MAKE) -f CMakeFiles/client-get.dir/build.make CMakeFiles/client-get.dir/net/NetManager.cpp.s
	$(MAKE) -f CMakeFiles/client-normal.dir/build.make CMakeFiles/client-normal.dir/net/NetManager.cpp.s
.PHONY : net/NetManager.cpp.s

net/cJSON.o: net/cJSON.c.o

.PHONY : net/cJSON.o

# target to build an object file
net/cJSON.c.o:
	$(MAKE) -f CMakeFiles/client_rtmp_admin.dir/build.make CMakeFiles/client_rtmp_admin.dir/net/cJSON.c.o
	$(MAKE) -f CMakeFiles/rtmp_cam_client.dir/build.make CMakeFiles/rtmp_cam_client.dir/net/cJSON.c.o
	$(MAKE) -f CMakeFiles/ForSUNSEV_IoTtest2.dir/build.make CMakeFiles/ForSUNSEV_IoTtest2.dir/net/cJSON.c.o
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/net/cJSON.c.o
	$(MAKE) -f CMakeFiles/client-put.dir/build.make CMakeFiles/client-put.dir/net/cJSON.c.o
	$(MAKE) -f CMakeFiles/client-get.dir/build.make CMakeFiles/client-get.dir/net/cJSON.c.o
	$(MAKE) -f CMakeFiles/client-normal.dir/build.make CMakeFiles/client-normal.dir/net/cJSON.c.o
.PHONY : net/cJSON.c.o

net/cJSON.i: net/cJSON.c.i

.PHONY : net/cJSON.i

# target to preprocess a source file
net/cJSON.c.i:
	$(MAKE) -f CMakeFiles/client_rtmp_admin.dir/build.make CMakeFiles/client_rtmp_admin.dir/net/cJSON.c.i
	$(MAKE) -f CMakeFiles/rtmp_cam_client.dir/build.make CMakeFiles/rtmp_cam_client.dir/net/cJSON.c.i
	$(MAKE) -f CMakeFiles/ForSUNSEV_IoTtest2.dir/build.make CMakeFiles/ForSUNSEV_IoTtest2.dir/net/cJSON.c.i
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/net/cJSON.c.i
	$(MAKE) -f CMakeFiles/client-put.dir/build.make CMakeFiles/client-put.dir/net/cJSON.c.i
	$(MAKE) -f CMakeFiles/client-get.dir/build.make CMakeFiles/client-get.dir/net/cJSON.c.i
	$(MAKE) -f CMakeFiles/client-normal.dir/build.make CMakeFiles/client-normal.dir/net/cJSON.c.i
.PHONY : net/cJSON.c.i

net/cJSON.s: net/cJSON.c.s

.PHONY : net/cJSON.s

# target to generate assembly for a file
net/cJSON.c.s:
	$(MAKE) -f CMakeFiles/client_rtmp_admin.dir/build.make CMakeFiles/client_rtmp_admin.dir/net/cJSON.c.s
	$(MAKE) -f CMakeFiles/rtmp_cam_client.dir/build.make CMakeFiles/rtmp_cam_client.dir/net/cJSON.c.s
	$(MAKE) -f CMakeFiles/ForSUNSEV_IoTtest2.dir/build.make CMakeFiles/ForSUNSEV_IoTtest2.dir/net/cJSON.c.s
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/net/cJSON.c.s
	$(MAKE) -f CMakeFiles/client-put.dir/build.make CMakeFiles/client-put.dir/net/cJSON.c.s
	$(MAKE) -f CMakeFiles/client-get.dir/build.make CMakeFiles/client-get.dir/net/cJSON.c.s
	$(MAKE) -f CMakeFiles/client-normal.dir/build.make CMakeFiles/client-normal.dir/net/cJSON.c.s
.PHONY : net/cJSON.c.s

rtmp_cam_client.o: rtmp_cam_client.cpp.o

.PHONY : rtmp_cam_client.o

# target to build an object file
rtmp_cam_client.cpp.o:
	$(MAKE) -f CMakeFiles/rtmp_cam_client.dir/build.make CMakeFiles/rtmp_cam_client.dir/rtmp_cam_client.cpp.o
.PHONY : rtmp_cam_client.cpp.o

rtmp_cam_client.i: rtmp_cam_client.cpp.i

.PHONY : rtmp_cam_client.i

# target to preprocess a source file
rtmp_cam_client.cpp.i:
	$(MAKE) -f CMakeFiles/rtmp_cam_client.dir/build.make CMakeFiles/rtmp_cam_client.dir/rtmp_cam_client.cpp.i
.PHONY : rtmp_cam_client.cpp.i

rtmp_cam_client.s: rtmp_cam_client.cpp.s

.PHONY : rtmp_cam_client.s

# target to generate assembly for a file
rtmp_cam_client.cpp.s:
	$(MAKE) -f CMakeFiles/rtmp_cam_client.dir/build.make CMakeFiles/rtmp_cam_client.dir/rtmp_cam_client.cpp.s
.PHONY : rtmp_cam_client.cpp.s

severmain.o: severmain.cpp.o

.PHONY : severmain.o

# target to build an object file
severmain.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/severmain.cpp.o
.PHONY : severmain.cpp.o

severmain.i: severmain.cpp.i

.PHONY : severmain.i

# target to preprocess a source file
severmain.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/severmain.cpp.i
.PHONY : severmain.cpp.i

severmain.s: severmain.cpp.s

.PHONY : severmain.s

# target to generate assembly for a file
severmain.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/severmain.cpp.s
.PHONY : severmain.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... client_rtmp_admin"
	@echo "... rtmp_cam_client"
	@echo "... edit_cache"
	@echo "... ForSUNSEV_IoTtest2"
	@echo "... server"
	@echo "... client-put"
	@echo "... client-get"
	@echo "... client-normal"
	@echo "... client-get.o"
	@echo "... client-get.i"
	@echo "... client-get.s"
	@echo "... client-normal.o"
	@echo "... client-normal.i"
	@echo "... client-normal.s"
	@echo "... client_rtmp_admin.o"
	@echo "... client_rtmp_admin.i"
	@echo "... client_rtmp_admin.s"
	@echo "... clienttest.o"
	@echo "... clienttest.i"
	@echo "... clienttest.s"
	@echo "... db/MySQL.o"
	@echo "... db/MySQL.i"
	@echo "... db/MySQL.s"
	@echo "... ffmpeg/ForSUNSEV_IoT.o"
	@echo "... ffmpeg/ForSUNSEV_IoT.i"
	@echo "... ffmpeg/ForSUNSEV_IoT.s"
	@echo "... ffmpeg/RTMPParallel.o"
	@echo "... ffmpeg/RTMPParallel.i"
	@echo "... ffmpeg/RTMPParallel.s"
	@echo "... ipfs/IPFSCtrl.o"
	@echo "... ipfs/IPFSCtrl.i"
	@echo "... ipfs/IPFSCtrl.s"
	@echo "... json/MsgFFmpeg.o"
	@echo "... json/MsgFFmpeg.i"
	@echo "... json/MsgFFmpeg.s"
	@echo "... json/MsgIPFS.o"
	@echo "... json/MsgIPFS.i"
	@echo "... json/MsgIPFS.s"
	@echo "... json/MsgMove.o"
	@echo "... json/MsgMove.i"
	@echo "... json/MsgMove.s"
	@echo "... logic/MsgHandler.o"
	@echo "... logic/MsgHandler.i"
	@echo "... logic/MsgHandler.s"
	@echo "... net/ByteArray.o"
	@echo "... net/ByteArray.i"
	@echo "... net/ByteArray.s"
	@echo "... net/CJsonObject.o"
	@echo "... net/CJsonObject.i"
	@echo "... net/CJsonObject.s"
	@echo "... net/ClientState.o"
	@echo "... net/ClientState.i"
	@echo "... net/ClientState.s"
	@echo "... net/MsgBase.o"
	@echo "... net/MsgBase.i"
	@echo "... net/MsgBase.s"
	@echo "... net/NetManager.o"
	@echo "... net/NetManager.i"
	@echo "... net/NetManager.s"
	@echo "... net/cJSON.o"
	@echo "... net/cJSON.i"
	@echo "... net/cJSON.s"
	@echo "... rtmp_cam_client.o"
	@echo "... rtmp_cam_client.i"
	@echo "... rtmp_cam_client.s"
	@echo "... severmain.o"
	@echo "... severmain.i"
	@echo "... severmain.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

